# Generated by Django 4.0 on 2022-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('series', models.CharField(max_length=10, verbose_name='Серия')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('date', models.CharField(max_length=25, verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('orderDatetime', models.DateTimeField(verbose_name='Время заказа')),
                ('status', models.CharField(choices=[('none', 'Не оплачено'), ('waiting', 'В ожидании'), ('paid', 'Оплачено'), ('error', 'Ошибка')], default='none', max_length=60, null=True, verbose_name='Статус заказа')),
                ('error', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ошибка')),
            ],
        ),
    ]
