# Generated by Django 4.0 on 2022-04-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_payorder_options_alter_payorder_orderdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='token',
            field=models.CharField(default=1, max_length=15, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
