# Generated by Django 4.0 on 2022-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_names_payorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
